package com.junly.dao;

import java.util.List;

import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.session.RowBounds;

import com.junly.model.TbSysUser;
import com.junly.model.TbSysUserExample;

public interface TbSysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user
     *
     * @mbg.generated
     */
    long countByExample(TbSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user
     *
     * @mbg.generated
     */
    int insert(TbSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user
     *
     * @mbg.generated
     */
    int insertSelective(TbSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user
     *
     * @mbg.generated
     */
    TbSysUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbSysUser record);
    
    @Select("select * from tb_sys_user")
    List<TbSysUser> selectList();
    
    
    
    @Select("select * from tb_sys_user")
    List<TbSysUser> selectList2(RowBounds row);
}