package com.junly.dao;

import com.junly.model.TbSysMenu;
import com.junly.model.TbSysMenuExample;

public interface TbSysMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_menu
     *
     * @mbg.generated
     */
    long countByExample(TbSysMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_menu
     *
     * @mbg.generated
     */
    int insert(TbSysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_menu
     *
     * @mbg.generated
     */
    int insertSelective(TbSysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_menu
     *
     * @mbg.generated
     */
    TbSysMenu selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbSysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbSysMenu record);
}